// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10.09.2025 21:43:12
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/-/Desktop/x/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/-/Desktop/x/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/-/Desktop/x/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/-/Desktop/x/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/-/Desktop/x/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/-/Desktop/x/frontend/composables/**/*.{js,ts,mjs}","C:/Users/-/Desktop/x/frontend/utils/**/*.{js,ts,mjs}","C:/Users/-/Desktop/x/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/-/Desktop/x/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/-/Desktop/x/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/-/Desktop/x/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;